#服务启动端口号
server:
  port: 9000

#MyBatis-Plus属性配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #配置日志打印


#MySql属性配置
spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/twohand?characterEncoding=utf-8&useSSL=false&serverTimezon=GMT%2B8 #mysql8以上要配置时区，东八区
    username: root
    password: xjying11

  #redis配置
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0



  #邮箱设置
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1290232854@qq.com
#    from: 1290232854@qq.com
#    properties.mail.smtp.port: 994 #465或者994
    #邮箱密码123aaa
    #授权码
    password: mgldiueyhckqfeff
#    properties.mail.smtp.auth: false
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  #文件上传大小限制
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB



#aliyun.oss文件服务器设置
#aliyun:
#  oss:
#    endpoint: oss-cn-beijing.aliyuncs.com
#    keyId: LTAI5tQPM4z8PPRudrqkJfy7
#    keySecret: YwnKglWT6ybZxQSo22j2jSIqkP1C1Q
#    bucketName: super-lawer

#管理员id设置
admin:
  id: 1

##案件文件默认路径前缀配置
#case:
#  file:
#    path:
#      prefix: ./caseFile/

